// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxG4y7kL8GVO5Fn244KueAFPCAOLe0vI8',
    appId: '1:113739012144:web:f82efc6d473c99003fb5f5',
    messagingSenderId: '113739012144',
    projectId: 'ssdealer-14f85',
    authDomain: 'ssdealer-14f85.firebaseapp.com',
    storageBucket: 'ssdealer-14f85.firebasestorage.app',
    measurementId: 'G-6WHR741S8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEhDmzByZXzqxL6ap2CAaP-MJXaHZnr8I',
    appId: '1:113739012144:android:81148285938943913fb5f5',
    messagingSenderId: '113739012144',
    projectId: 'ssdealer-14f85',
    storageBucket: 'ssdealer-14f85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd5DpBvW1Ue33F0EzOzSE_wyvYSsOAevY',
    appId: '1:113739012144:ios:7e6f23687e2336f33fb5f5',
    messagingSenderId: '113739012144',
    projectId: 'ssdealer-14f85',
    storageBucket: 'ssdealer-14f85.firebasestorage.app',
    iosBundleId: 'com.example.spaceSolarDealer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd5DpBvW1Ue33F0EzOzSE_wyvYSsOAevY',
    appId: '1:113739012144:ios:7e6f23687e2336f33fb5f5',
    messagingSenderId: '113739012144',
    projectId: 'ssdealer-14f85',
    storageBucket: 'ssdealer-14f85.firebasestorage.app',
    iosBundleId: 'com.example.spaceSolarDealer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxG4y7kL8GVO5Fn244KueAFPCAOLe0vI8',
    appId: '1:113739012144:web:dd02fdfe92741a073fb5f5',
    messagingSenderId: '113739012144',
    projectId: 'ssdealer-14f85',
    authDomain: 'ssdealer-14f85.firebaseapp.com',
    storageBucket: 'ssdealer-14f85.firebasestorage.app',
    measurementId: 'G-2ZQ03639J9',
  );
}
